name: fs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: update
      run: sudo apt-get update
    - name: libzip
      run: sudo apt-get install libzip-dev
    - name: make
      run: make dirs && make GCC="g++-10" lib_fs
